### ISSUE TITLE
A few Warnings and one Question

### ISSUE THREAD

**Issue by filly86** [tissot/erlang-html5-chatroom#1]
First of all: Great Project. I am impressed with the simplicity of your source code! Here is what i found while running your server:
- I installed newest OTP R16B03 on Windows. 
- While compiling  "html5.erl" i get following warning: 
  "html5.erl:15: Warning: crypto:sha/1 is deprecated and will be removed in in a future  
  release; use crypto:hash/2"
  Could you fix this?

Then i noticed something strange: If i try to send 5000 characters just 1452 are transfered to other chat users. For me it seams like your server is not able to handle continuation frames. Could you look after that?

Kind Regards
Fil

**Comment by qinlai** [comment]
Thank you for review, i have fixed the issues.
